### ISSUE TITLE
Segmentation fault in makePermutation of graph

### ISSUE THREAD

**Issue by Ezbob** [jakobandersen/mod#2]
Happens when I run PyMod with the following strategy code:

```
strategy = (                                                          
        addSubset(level) >>                
        addSubset(level.makePermutation()) >>        
        repeat(          
                revive(mark)     
                >> repeat(reattachExternal)    
                >> repeat({ removeAttached, removeInterR })              
                >> repeat(removeR)             
                >> unmark                                                      
        )                                                                                            
)     
```

The fault message is as follows:

```
RNG seed: 868299854
/home/jlandersen/shared/bin/mod: line 179: 22710 Segmentation fault      "$@"

```

**Comment by jakobandersen** [comment]
Thanks for reporting! The input is not being checked properly so a pointer is dangling.
What should happen is that you get an exception when the strategy is passed to `dgRuleComp` because of bad input: the graph `level` is isomorphic to its permutation, which you get from `level.makePermutation()`. Each graph object in a derivation graph must be unique, up to isomorphism.

**Comment by Ezbob** [comment]
Ah.. Thanks for the response. I have revised the strategy and arrived at a better solution. Hope this helps in debugging.
